packages/ic-response-verification/src/validation/v2_validation.rs

paths that do not exist in the tree should return false even if there is not a more precise path in the tree, make sure that a more specific expr_path with wildcards is accounted for, do not allow expr_path that do not end with a valid suffix
re #TT-197

fix: expr_path validation fixes

---

.github/workflows/release.yml

According to the docs: https://github.com/ncipollo/release-action
> An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
The last release still didn't include the artifacts so hopefully this fixes it.

ci: fix artifacts patterns for the create release action

---

packages/ic-response-verification-wasm/Cargo.lock
packages/ic-response-verification-wasm/Cargo.toml

`wasm-bindgen-console-logger` v0.2.0 seems to have been pulled from crates.io.
https://docs.rs/wasm-bindgen-console-logger/latest/wasm_bindgen_console_logger/

ci: correct the wasm-bindgen-console-logger version

---

Cargo.lock
packages/ic-response-verification-test-utils/Cargo.toml
packages/ic-response-verification-test-utils/src/encoding.rs
packages/ic-response-verification/tests/v2_response_verification_certification_scenarios.rs
packages/ic-response-verification/tests/v2_response_verification_sad_path.rs

add tests to cover fallback, redirect, content-negotiation and etag caching scenarios

test: add v2 happy path non-essential tests

---

.github/workflows/create-release-pr.yml
.github/workflows/release.yml

This PR should have all the necessary changes so that the `ic-representation-independent-hash` crate can be published on crates.io.

ci: configure CI to publish the ic-representation-independent-hash crate

---

packages/ic-representation-independent-hash/src/lib.rs
packages/ic-representation-independent-hash/src/representation_independent_hash.rs

Support `Vec<u8>` values for representation independent hash

feat(hash): add support for byte values

---

.github/CODEOWNERS
.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
README.md

These docs are based on the same docs from motoko base: https://github.com/dfinity/motoko-base
Code of conduct is the same, but contributions has been altered slightly

docs: add required documentation for opening to external contributions

---

packages/ic-response-verification/src/error.rs
packages/ic-response-verification/src/types/verification_result.rs
packages/ic-response-verification/src/verification/verify_request_response_pair.rs
packages/ic-response-verification/tests/v1_response_verification.rs
packages/ic-response-verification/tests/v2_response_verification_certification_scenarios.rs
packages/ic-response-verification/tests/v2_response_verification_sad_path.rs

Updated the verification error handling to include a reason when verification fails. This now means that all verification related issues are not thrown anymore, instead they are include in the `reason` property of the response.
The errors that are still thrown are now related to the parsing logic before the [verification](https://github.com/dfinity/response-verification/blob/kepler/tt-79-errors/packages/ic-response-verification/src/verification/verify_request_response_pair.rs#L83) method is called upon or the verification version is not supported (this case still results in the error `UnsupportedVerificationVersion`)

(refactor: TT-79) Standardize verification errors as reasons

---

examples/rust/src/main.rs
packages/ic-response-verification-tests/src/main.rs
packages/ic-response-verification-tests/wasm-tests/main.ts
packages/ic-response-verification-wasm/Cargo.lock
packages/ic-response-verification/Cargo.toml
packages/ic-response-verification/src/hash/request_hash.rs
packages/ic-response-verification/src/hash/response_hash.rs
packages/ic-response-verification/src/types/request.rs
packages/ic-response-verification/src/types/response.rs
packages/ic-response-verification/tests/v1_response_verification.rs
packages/ic-response-verification/tests/v2_response_verification_certification_scenarios.rs
packages/ic-response-verification/tests/v2_response_verification_happy_path.rs
packages/ic-response-verification/tests/v2_response_verification_sad_path.rs

Request body hashing is part of the spec, but has not been part of the implementation: https://github.com/dfinity/interface-spec/blob/master/spec/http-gateway-protocol-spec.md#request-hash-calculation
Thankfully nobody is using this yet 🙃

fix: add missing request body hashing

---

packages/ic-response-verification-wasm/Cargo.lock
packages/ic-response-verification-wasm/Cargo.toml
packages/ic-response-verification-wasm/src/lib.rs

File size before any changes: 231kb
After adding logger and panic hook: 238kb
So that's an additional 7kb.
After reverting back to the default allocator: 244kb
So that's an additional 6kb.
Totaling an extra 13kb. I don't think anyone will notice :)

feat: enable web logs and panic hook for response verification library

---

packages/ic-response-verification-tests/src/main.rs
packages/ic-response-verification-tests/wasm-tests/main.ts
packages/ic-response-verification-wasm/src/lib.rs
packages/ic-response-verification/src/cbor/hash_tree.rs
packages/ic-response-verification/src/test_utils.rs
packages/ic-response-verification/src/types/verification_result.rs
packages/ic-response-verification/src/validation/common_validation.rs
packages/ic-response-verification/src/validation/v2_validation.rs
packages/ic-response-verification/src/verification/certificate_header_field.rs
packages/ic-response-verification/src/verification/verify_request_response_pair.rs
packages/ic-response-verification/tests/v1_response_verification.rs
packages/ic-response-verification/tests/v2_response_verification_certification_scenarios.rs
packages/ic-response-verification/tests/v2_response_verification_happy_path.rs
packages/ic-response-verification/tests/v2_response_verification_sad_path.rs

This PR updates the return type to always be a result/exception, instead of only for "unexpected" scenarios.
There are also some Cargo clippy fixes and a fix for the e2e tests that allowed broken e2e tests to pass in a previous PR: https://github.com/dfinity/response-verification/actions/runs/5737416933/job/15549030697

feat: always return a result/exception when response verification fails

---

packages/ic-response-verification/src/types/request.rs

re #TT-300
Query strings were being decoded the same way as the entire URL which would break the URI format, this fixes it by handling the path and query string differently.

fix: url decoding for encoded query strings

---

.cz.yaml
.github/workflows/create-release-pr.yml
.github/workflows/release.yml
Cargo.lock
Cargo.toml
README.md
packages/ic-cbor/Cargo.toml
packages/ic-certificate-verification/Cargo.toml
packages/ic-certification/Cargo.toml
packages/ic-certification/LICENSE
packages/ic-certification/README.md
packages/ic-certification/src/certificate.rs
packages/ic-certification/src/hash_tree/mod.rs
packages/ic-certification/src/hash_tree/tests.rs
packages/ic-certification/src/lib.rs
packages/ic-response-verification-test-utils/Cargo.toml
packages/ic-response-verification-wasm/Cargo.lock
packages/ic-response-verification/Cargo.toml
packages/ic-response-verification/src/error.rs

This moves the `ic-certification` library from https://github.com/dfinity/agent-rs.
I haven't made any code changes, although I made some slight alterations to the `Cargo.toml`. All changes outside of the `ic-certification` folder are the usual checklist items for adding new packages.

feat: add ic-certification library

---

.github/workflows/release.yml
packages/ic-certification-testing-wasm/README.md
packages/ic-certification-testing/README.md

We were asked about [publishing the ic-certification](https://dfinity.slack.com/archives/C03P8DZ2PTJ/p1698414327916929) library. Unfortunately we can't due to Git dependencies in the main IC repo, but I've added the step anyway with some comments explaining why it's not published yet. I also added some missing usage docs and the publish steps for the JS counterpart. I also added the step for `@dfinity/certificate-verification` because it was missing. `ic-certificate-verification` is already published.

ci: publish certification-testing and certificate-verification libraries

---

packages/ic-http-certification/README.md
packages/ic-http-certification/src/cel/cel_builder.rs
packages/ic-http-certification/src/cel/cel_types.rs
packages/ic-http-certification/src/cel/create_cel_expr.rs
packages/ic-http-certification/src/lib.rs

When integrating `ic-http-certification` into `ic-response-verification`, I ran into issues with managing lifetimes because the `DefaultRequestCertification` and `DefaultResponseCertification` structs are holding references to data, instead of owning it.
This causes problems when you want to return a reference to data that is owned by the current function. Using copy on write ([COW](https://doc.rust-lang.org/std/borrow/enum.Cow.html)) for the properties on these structs allows us to keep the advantage of holding references to data while allowing the struct to take ownership of data in those cases where it's needed.
I split this PR out from the changes in `ic-response-verification` to make the PR smaller.

feat: add copy on write support to CEL definition types

---

packages/ic-http-certification/src/cel/create_cel_expr.rs
packages/ic-http-certification/src/cel/fixtures.rs

After finishing the integration with the `ic-response-verification` the tests started failing because the CEL expressions were not valid 🙃

fix: missing certification object in CEL expressions

---

.vscode/settings.json
Cargo.lock
packages/ic-http-certification/README.md
packages/ic-http-certification/src/cel/cel_builder.rs
packages/ic-http-certification/src/cel/cel_types.rs
packages/ic-http-certification/src/cel/create_cel_expr.rs
packages/ic-http-certification/src/hash/mod.rs
packages/ic-http-certification/src/hash/request_hash.rs
packages/ic-http-certification/src/hash/response_hash.rs
packages/ic-http-certification/src/lib.rs
packages/ic-http-certification/src/tree/certification.rs
packages/ic-http-certification/src/tree/mod.rs
packages/ic-response-verification/src/cel/ast_mapping.rs
packages/ic-response-verification/src/cel/tests.rs
packages/ic-response-verification/src/validation/v2_validation.rs
packages/ic-response-verification/src/verification/verify_request_response_pair.rs
packages/ic-response-verification/tests/v2_response_verification_certification_scenarios.rs
packages/ic-response-verification/tests/v2_response_verification_happy_path.rs
packages/ic-response-verification/tests/v2_response_verification_sad_path.rs

improve underlying cel structures to prevent invalid cel expressions from being created

feat(ic-http-certification): add certification builder

---

Cargo.lock
Cargo.toml
packages/ic-certification-testing/src/error.rs

Commits pulled from https://github.com/dfinity/response-verification/pull/272 to rewrite the commit messages to be commitizen compliant.

chore: update ic repo references

---

examples/rust/src/main.rs
packages/ic-cbor/src/cbor_parser.rs
packages/ic-http-certification/README.md
packages/ic-http-certification/src/hash/response_hash.rs
packages/ic-http-certification/src/http/http_response.rs
packages/ic-http-certification/src/lib.rs
packages/ic-http-certification/src/tree/certification.rs
packages/ic-http-certification/src/tree/mod.rs
packages/ic-response-verification-tests/src/main.rs
packages/ic-response-verification-wasm/src/response.rs
packages/ic-response-verification/tests/v1_response_verification.rs
packages/ic-response-verification/tests/v2_response_verification_certification_scenarios.rs
packages/ic-response-verification/tests/v2_response_verification_happy_path.rs
packages/ic-response-verification/tests/v2_response_verification_sad_path.rs

Add the `upgrade` property on the `HttpResponse` object. Also rename `Certification` to `HttpCertification`.

feat(ic-http-certification): add upgrade property to HttpResponse struct

---

packages/ic-representation-independent-hash/src/representation_independent_hash.rs

The current implementation is missing support for `Array`-values, this PR adds this support.

feat: add support for hashing arrays of Value-objects

---

packages/ic-certificate-verification/Cargo.toml

This dependency caused the publish pipeline to fail because it's a git dependency: https://github.com/dfinity/response-verification/actions/runs/8357624688/job/22877166656.
Fortunately it's not actually used outside of tests, so the fix is simply moving to `dev-dependencies`.

fix(ic-certificate-verification): redundant dependency

---

examples/http-certification/assets/README.md
examples/http-certification/assets/src/backend/src/lib.rs
packages/ic-asset-certification/README.md
packages/ic-asset-certification/src/asset_router.rs
packages/ic-asset-certification/src/lib.rs

This is a little tricky because we can't `Rc::clone()` inside of `thread_local`, so we'd need to use `lazy_static` and `Arc<Mutex<T>>` instead of `thread_local` and `Rc<RefCell<T>>`.
I've no issue with using `lazy_static` but `Arc` feels weird because it's a thread-safe primitive meant for multi-threaded environments and I think it could be confusing for developers why those primitives are necessary.
So I opted to use a non-static approach and allow for the tree to be replaced _after_ initialization of the asset router inside the `init` hook of the canister.

feat(ic-asset-certification): optionally init asset router with HTTP Certification tree

---

packages/ic-http-certification/src/lib.rs
packages/ic-http-certification/src/tree/certification_tree.rs
packages/ic-http-certification/src/tree/certification_tree_path.rs
packages/ic-http-certification/src/utils/mod.rs
packages/ic-http-certification/src/utils/wildcard_paths.rs
packages/ic-response-verification/src/validation/v2_validation.rs

This fixes an issue where wildcard paths that fully match the request URL were not witnessed.
For example, if you request `["foo", "bar", "baz"]` and respond with `["foo", "bar", "<*>"]` then you will be missing the witness for `["foo", "var", "baz", "<*>"]`.
This logic can actually be shared with similar code from `ic-response-verification`, so rather than changing the current code I refactored the `ic-response-verification` implementation to a common function.

fix(ic-http-certification): ensure all possible wildcards are witnessed

---

examples/http-certification/assets/src/backend/src/lib.rs
packages/ic-asset-certification/src/asset.rs
packages/ic-asset-certification/src/asset_router.rs

This is an initial PR for adding support for alternative response encodings, Gzip, brotli etc...
It works and is fully tested, but I'm not entirely happy with the interface. It currently requires adding additional configuration entries for the encoded versions, and I'd like to improve that but I still haven't fully decided how a better interface will look.
In the meantime it would be nice to merge it in it's current state and then re-iterate on the interface in a future PR.

feat(ic-asset-certification): add support for alt response encodings

---

packages/ic-asset-certification/README.md

This is to ensure the docusaurus compiler doesn't throw an error when compiling markdown for the portal

chore: escape curly bracket in README

---

packages/ic-asset-certification/Cargo.toml
packages/ic-cbor/Cargo.toml
packages/ic-certificate-verification/Cargo.toml
packages/ic-certification-testing/Cargo.toml
packages/ic-certification/Cargo.toml
packages/ic-http-certification/Cargo.toml
packages/ic-representation-independent-hash/Cargo.toml
packages/ic-response-verification/Cargo.toml

The release pipeline has [failed](https://github.com/dfinity/response-verification/actions/runs/10078240807/job/27862694811) because the `hash` category seems to have been removed from crates.io, although I can't find any explanation as to when or why that happened.
I took the time to review the categories of all crates just in case there's other examples, but there wasn't. So not all changes are necessary but I think the categories make more sense now.

chore: remove outdated crate categories

---

packages/ic-asset-certification/src/asset_router.rs

Using response header exclusions as a more secure default has been encouraged by ProdSec in previous security reviews. In this case it's really the same either way because we certify every header that's added to the response, but it simplifies the code by using an empty array of exclusions that a full array on inclusions.
I did not add support for excluding response headers since it's currently not possible to return a dynamic response header anyway. If that use case comes up then I think we should revisit the idea then.

feat(ic-asset-certification): use response header exclusions instead of inclusions for better security

---

packages/ic-asset-certification/README.md
packages/ic-asset-certification/src/asset_router.rs
packages/ic-asset-certification/src/lib.rs
packages/ic-http-certification/src/http/http_response.rs
packages/ic-response-verification/src/verification/verify_request_response_pair.rs

TT-415
Adds the ability to delete certified assets from the asset router.

feat(ic-asset-ceritication): allow deleting assets from the asset router

---

Cargo.lock
examples/http-certification/assets/README.md
examples/http-certification/assets/dfx.json
examples/http-certification/assets/src/backend/Cargo.toml
examples/http-certification/assets/src/backend/src/lib.rs
examples/http-certification/custom-assets/README.md
examples/http-certification/custom-assets/dfx.json
examples/http-certification/custom-assets/src/backend/Cargo.toml
examples/http-certification/custom-assets/src/backend/src/lib.rs
examples/http-certification/json-api/README.md
examples/http-certification/json-api/src/backend/Cargo.toml
examples/http-certification/json-api/src/backend/src/lib.rs
packages/ic-asset-certification/README.md
packages/ic-asset-certification/src/asset_router.rs
packages/ic-asset-certification/src/lib.rs
packages/ic-certification/Cargo.toml
packages/ic-http-certification-tests/tests/v1_response_verification.rs
packages/ic-http-certification-tests/tests/v2_response_verification_certification_scenarios.rs
packages/ic-http-certification-tests/tests/v2_response_verification_happy_path.rs
packages/ic-http-certification-tests/tests/v2_response_verification_sad_path.rs
packages/ic-http-certification/Cargo.toml
packages/ic-http-certification/src/hash/response_hash.rs
packages/ic-http-certification/src/lib.rs
packages/ic-http-certification/src/tree/certification.rs
packages/ic-http-certification/src/tree/certification_tree.rs
packages/ic-http-certification/src/tree/certification_tree_entry.rs
packages/ic-http-certification/src/utils/mod.rs
packages/ic-http-certification/src/utils/response_header.rs

removed serde feature from ic-http-certification, condensed serde_bytes into serde feature of ic-certification
BREAKING CHANGE: removed serde feature from ic-http-certification, condensed serde_bytes into serde feature of ic-certification.
TT-426

feat(ic-http-certification): add add_certificate_header util function

---

Cargo.lock
examples/http-certification/assets/README.md
examples/http-certification/assets/src/backend/src/lib.rs
examples/http-certification/custom-assets/README.md
examples/http-certification/custom-assets/src/backend/src/lib.rs
examples/http-certification/json-api/README.md
examples/http-certification/json-api/src/backend/src/lib.rs
packages/ic-asset-certification/Cargo.toml
packages/ic-asset-certification/src/asset_router.rs
packages/ic-asset-certification/src/lib.rs
packages/ic-http-certification/src/utils/response_header.rs
packages/ic-response-verification-test-utils/src/encoding.rs
packages/ic-response-verification/src/lib.rs
packages/ic-response-verification/src/verification/certificate_header.rs
packages/ic-response-verification/src/verification/mod.rs
packages/ic-response-verification/src/verification/verify_request_response_pair.rs

feat(ic-asset-certification): integrate add_certificate_header into the library so consumers do not need to call it manually

---

packages/ic-asset-certification/src/asset_router.rs
packages/ic-certification/src/hash_tree/mod.rs
packages/ic-certification/src/nested_rb_tree.rs
packages/ic-certification/src/rb_tree/mod.rs
packages/ic-http-certification/src/tree/certification_tree.rs

Add certification for individual chunks to the certification tree.
Additionally, add human-readable implementations of `Debug`-trait for HttpCertificationTree and related structs, to simplify debugging.
This PR supersedes PR #384

feat(ic-asset-certification): add certification for individual chunks

---

packages/ic-asset-certification/src/asset_router.rs

Add `Range` to certification of requests for chunked (long) assets.

feat(ic-asset-certification): add Range as a certified request header

---

examples/http-certification/custom-assets/README.md
examples/http-certification/json-api/README.md
examples/http-certification/json-api/src/backend/src/lib.rs
examples/http-certification/upgrade-to-update-call/README.md
packages/ic-http-certification/src/http/http_request.rs
packages/ic-http-certification/src/http/http_response.rs
packages/ic-response-verification-wasm/src/request.rs

I took a very similar approach here as I did for response status code. Thankfully there's a lot less sweeping changes in this case though.
Additionally I noticed that I missed some docs that should've been updated with the status code change, so I fixed them too.

feat(ic-http-certification): add request method enum

---

Cargo.lock
Cargo.toml
packages/ic-asset-certification/Cargo.toml
packages/ic-asset-certification/src/asset_router.rs
packages/ic-asset-certification/tests/common/mod.rs
packages/ic-asset-certification/tests/large_assets.rs
packages/ic-http-certification-tests/Cargo.toml
packages/ic-http-certification-tests/tests/v1_response_verification.rs
packages/ic-http-certification-tests/tests/v2_response_verification_certification_scenarios.rs
packages/ic-http-certification-tests/tests/v2_response_verification_happy_path.rs
packages/ic-http-certification-tests/tests/v2_response_verification_sad_path.rs
packages/ic-http-certification/src/http/http_request.rs
packages/ic-response-verification/Cargo.toml
packages/ic-response-verification/src/error.rs
packages/ic-response-verification/src/validation/common_validation.rs
packages/ic-response-verification/src/validation/v2_validation.rs
packages/ic-response-verification/src/verification/certificate_header.rs
packages/ic-response-verification/src/verification/verify_request_response_pair.rs

add additional error types to ic-response-verification crate

fix(ic-asset-certification): fix range response certification

---

.github/workflows/build-and-test.yml
.github/workflows/commitizen.yml
.github/workflows/create-release-pr.yml
.github/workflows/e2e-tests.yml
.github/workflows/release.yml
dfx.json
examples/http-certification/assets/src/tests/jest.config.ts
examples/http-certification/assets/src/tests/src/http.spec.ts
examples/http-certification/assets/src/tests/src/wasm.ts
examples/http-certification/custom-assets/src/tests/jest.config.ts
examples/http-certification/custom-assets/src/tests/src/http.spec.ts
examples/http-certification/custom-assets/src/tests/src/wasm.ts
examples/http-certification/json-api/src/tests/jest.config.ts
examples/http-certification/json-api/src/tests/src/todos.spec.ts
examples/http-certification/json-api/src/tests/src/wasm.ts
examples/http-certification/skip-certification/src/tests/jest.config.ts
examples/http-certification/skip-certification/src/tests/src/http.spec.ts
examples/http-certification/skip-certification/src/tests/src/wasm.ts
examples/http-certification/upgrade-to-update-call/src/tests/jest.config.ts
examples/http-certification/upgrade-to-update-call/src/tests/src/http.spec.ts
examples/http-certification/upgrade-to-update-call/src/tests/src/wasm.ts
package.json
pnpm-lock.yaml
scripts/e2e.sh

To address a [breaking change](https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts) in github and fix failing tests.

chore: bump sccache-actions to v0.0.9

---

examples/http-certification/json-api/src/backend/src/types.rs

When I copied the code over, I got following build warning:
```
warning: elided lifetime has a name
--> src/orbiter/src/http/impls.rs:6:42
|
5 | impl<'a, T: Serialize> ApiResponse<'a, T> {
|      -- lifetime `'a` declared here
6 |     pub fn ok(data: &'a T) -> ApiResponse<T> {
|                                          ^ this elided lifetime gets resolved as `'a`
|
= note: `#[warn(elided_named_lifetimes)]` on by default
```
Therefore thought about providing a PR to pass the lifetime along in the example.

chore: resolve elided lifetime warning in json-api example

---

.github/workflows/generate-changelog.yml

The new version of `dfinity/ci-tools/.github/workflows/generate-changelog.yaml` requires a GitHub environment. So this adapts the `generate_changelog` workflow to use the newly created `create-prs` environment which specifies the required `PR_AUTOMATION_BOT_PUBLIC_PRIVATE_KEY` secret.

chore: adapt generate_changelog to retrieve the secret from the GitHub environment
